index:
   path: /
   controller: App\Controller\WordController::index
   methods: [ GET ]

word_submit:
    path: /word/submit
    controller: App\Controller\WordController::submit
    methods: [ POST ]